events {}

http {

    upstream django_backend {

        least_conn;

        server django1:8000;
        server django2:8000;
    }

    server {

        listen 80;

        client_max_body_size 100M;

        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;

        location /static/ {
            alias /app/static/;
        }

        location /media/ {
            alias /app/media/;
        }

        location / {

            proxy_pass http://django_backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_redirect off;
        }
    }
}